# Generated by Django 2.2.6 on 2021-03-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll', models.CharField(max_length=12)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('dept', models.CharField(max_length=20)),
                ('grad_year', models.IntegerField(blank=True)),
            ],
        ),
    ]
