# Generated by Django 2.2.6 on 2021-03-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMPApp', '0003_auto_20210310_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='Image', null=True, upload_to='avatars'),
        ),
    ]
