# Generated by Django 2.2.6 on 2021-03-18 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMPApp', '0004_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=50, null=True)),
                ('Category', models.CharField(blank=True, max_length=50, null=True)),
                ('DP', models.ImageField(blank=True, upload_to='book_image')),
                ('Description', models.TextField(default='')),
                ('Type', models.CharField(default='Free', max_length=50)),
                ('Price', models.IntegerField(default=0)),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
