# Generated by Django 2.2.6 on 2021-03-21 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CMPApp', '0006_resource_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
