# Generated by Django 2.2.6 on 2021-03-21 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMPApp', '0007_resource_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='resource',
            name='DP',
            field=models.ImageField(blank=True, upload_to='book_image/'),
        ),
        migrations.RemoveField(
            model_name='resource',
            name='user',
        ),
        migrations.AddField(
            model_name='resource',
            name='user',
            field=models.ForeignKey(blank=True, default=170210107009, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
