# Generated by Django 2.2.6 on 2021-03-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMPApp', '0009_auto_20210321_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegedata',
            name='grad_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='collegedata',
            name='lname',
            field=models.CharField(max_length=20),
        ),
    ]
