# Generated by Django 2.2.6 on 2021-03-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMPApp', '0010_auto_20210327_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dept',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='grad_year',
            field=models.IntegerField(null=True),
        ),
    ]
