# Generated by Django 2.2.6 on 2021-03-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMPApp', '0011_auto_20210327_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avtar',
            field=models.ImageField(blank=True, upload_to='user_image/'),
        ),
    ]
