# Generated by Django 2.2.6 on 2021-03-27 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMPApp', '0012_userprofile_avtar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='Branch',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='Category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='DP',
            field=models.ImageField(upload_to='book_image/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='Title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='requestedResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req', models.CharField(max_length=12, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('res', models.CharField(max_length=50)),
                ('don', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
