# Generated by Django 2.2.6 on 2021-03-27 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMPApp', '0015_auto_20210327_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestedresources',
            old_name='uploaded_at',
            new_name='created_on',
        ),
        migrations.AlterField(
            model_name='requestedresources',
            name='don',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='requestedresources',
            name='req',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
