# Generated by Django 2.2.6 on 2021-04-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMPApp', '0016_auto_20210327_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='isbn',
            field=models.CharField(default='NA', max_length=20, null=True),
        ),
    ]
